name: easy-forum

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Go 语言环境
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'  # 使用你项目的 Go 版本

      # 编译 Go 项目为二进制文件
      - name: Build project
        run: go build main.go  # 将项目编译为可执行文件

      # 上传二进制文件到服务器
      - name: Upload binary to server via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}  # 服务器 IP 或域名
          username: ${{ secrets.SERVER_USER }}  # SSH 用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secrets 中存储的 SSH 私钥
          source: "main"  # 二进制文件
          target: "/opt/go/easy-forum"  # 上传到服务器的路径

      # 配置并重启 systemd 服务
      - name: restart systemd service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
             # 设置权限
             sudo chmod 740 /opt/go/easy-forum/main
            
             # 启动或重启服务
             sudo systemctl restart easy-forum.service


